### ISSUE TITLE
What is the correct way to handle timestamps around leap seconds?

### ISSUE THREAD

**Issue by pkhuong** [aws/clock-bound#17]
In this announcement post https://aws.amazon.com/blogs/compute/its-about-time-microsecond-accurate-clocks-on-amazon-ec2-instances/ , we learn that the PTP clock will not provide smeared time in case of a leap second. The same announcement links to clock-bound.

I was relieved to see clock-bound offers predicates that determine whether a timestamp is definitely in the past or the future: that's a tricky operation with leap seconds. However, I don't see where leap seconds are handled in the clock-bound daemon. Is that implicit in the clock error bound (i.e., does the bound grow to more than 1 second around leap seconds)?

How should a client application determine whether timestamps are squarely in the past or in the future, around a positive or negative leap second?

**Comment by notjustjoshin** [comment]
The biggest thing is being consistent in the trusted source (or sources) of time that you use. You do not want to mix "smeared" and "non-smeared" time.

That way the two timestamps you are comparing are both smeared (and make sure the smearing is the same way, as in both 24-hour linear not liner versus sinusoidal smearing) or both not smeared. AWS does not smear the PTP hardware clocks (PHCs) because these are precise devices and precision-smeared is a bit of an oxymoron.

The good news is leap smearing is going away: https://www.bipm.org/en/cgpm-2022/resolution-4, so in the future there will not be this mix. Another important thing to note is that these events are rare and you have a heads up if a leap second is coming; the last one leap second was in 2017 and there is not one planned in 2024.
